# Generated by Django 5.0.7 on 2024-07-20 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('belt', models.CharField(max_length=255)),
                ('days', models.CharField(max_length=255)),
                ('enrollDate', models.CharField(max_length=255)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_today', models.DateTimeField(null=True)),
                ('ssn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herf.students')),
            ],
        ),
    ]
