# Generated by Django 5.0.7 on 2024-07-20 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daysNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0)),
                ('ssn_15', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herf.students')),
            ],
        ),
    ]
